In [2]:
import pandas as pd
import numpy as np

In [3]:
customer_behavior_features = pd.read_parquet(
    "/kaggle/input/datasets/selinparmar/dataset-features/customer_behavior_features.parquet"
)

article_features = pd.read_parquet(
    "/kaggle/input/datasets/selinparmar/dataset-features/article_features.parquet"
)

transactions = pd.read_parquet(
    "/kaggle/input/datasets/selinparmar/dataset-features/transactions_cleaned.parquet"
)

print("Datasets loaded!")

Datasets loaded!

In [4]:
#create time features
transactions['year'] = (
    transactions['t_dat']
    .dt.year
)

transactions['month'] = (
    transactions['t_dat']
    .dt.month
)

transactions['day_of_week'] = (
    transactions['t_dat']
    .dt.day_name()
)

In [5]:
#create interaction label
transactions[
    'interaction_label'
] = 1

In [6]:
transactions_sample = (
    transactions
    .sample(
        n=1000000,
        random_state=42
    )
)

print(
    transactions_sample.shape
)

(1000000, 9)

In [7]:
training_df = (
    transactions_sample
    .merge(
        customer_behavior_features,
        on='customer_id',
        how='left'
    )
)

training_df.head()

,t_dat,customer_id,article_id,price,sales_channel_id_x,year,month,day_of_week,interaction_label,FN,...,age,postal_code,purchase_frequency,days_since_last_purchase,avg_spend,avg_days_between_purchases,product_type_name,season,sales_channel_id_y,repeat_purchase_ratio
0,2019-10-03,0bae744d492a1ee45460ef798a977b33ffa09f14f92cf6...,632307002,0.016932,1,2019,10,Thursday,1,1.0,...,23.0,2c29ae653a9282cce4151bd87643c907644e09541abc28...,8.0,295.0,0.030057,13.857143,Blazer,Autumn,1.0,0.000000
1,2019-11-17,a076c84a1df6ecdb4f21bd6bac49ac5e6704aa48340b7c...,688728003,0.021593,2,2019,11,Sunday,1,1.0,...,44.0,0cca6e874f2f0eb47c6940ef39bb2fb0825a6450379c44...,126.0,11.0,0.024303,5.560000,Trousers,Autumn,2.0,0.067797
2,2019-06-23,e1262cea5799e7f866272c5b54aeab5641e62926a4bffe...,524529007,0.015237,1,2019,6,Sunday,1,0.0,...,48.0,2c29ae653a9282cce4151bd87643c907644e09541abc28...,18.0,457.0,0.018544,0.000000,Vest top,Summer,1.0,0.000000
3,2020-01-02,17c6855702b6e50f732bee25ef6789927dc3cb61161dfc...,800529001,0.010153,2,2020,1,Thursday,1,1.0,...,32.0,db07c4609b0d4d6894dda3ccedc2dc45a00d4a9af7daa5...,219.0,6.0,0.026946,3.041284,Dress,Summer,2.0,0.038095
4,2019-07-23,1342bda603bf7ae79af2595951f069db1b50a3cc5dbcc4...,758129001,0.030492,2,2019,7,Tuesday,1,0.0,...,28.0,753d7c844f178a57651900a2e14bf31b4e5aab01517e54...,97.0,17.0,0.033973,7.281250,Dress,Winter,2.0,0.054348

In [8]:
training_df = (
    training_df
    .merge(
        article_features,
        on='article_id',
        how='left'
    )
)

training_df.head()

,t_dat,customer_id,article_id,price,sales_channel_id_x,year,month,day_of_week,interaction_label,FN,...,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc,purchase_count
0,2019-10-03,0bae744d492a1ee45460ef798a977b33ffa09f14f92cf6...,632307002,0.016932,1,2019,10,Thursday,1,1.0,...,A,Ladieswear,1,Ladieswear,11,Womens Tailoring,1005,Jersey Fancy,"Sleeveless top in jersey crêpe with a small, g...",1846.0
1,2019-11-17,a076c84a1df6ecdb4f21bd6bac49ac5e6704aa48340b7c...,688728003,0.021593,2,2019,11,Sunday,1,1.0,...,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Jersey hipster briefs with a low waist, lined ...",3013.0
2,2019-06-23,e1262cea5799e7f866272c5b54aeab5641e62926a4bffe...,524529007,0.015237,1,2019,6,Sunday,1,0.0,...,D,Divided,2,Divided,53,Divided Collection,1003,Knitwear,Short top in a soft rib knit in a narrow cut a...,1234.0
3,2020-01-02,17c6855702b6e50f732bee25ef6789927dc3cb61161dfc...,800529001,0.010153,2,2020,1,Thursday,1,1.0,...,D,Divided,2,Divided,53,Divided Collection,1009,Trousers,Trousers in cotton twill with a high paper bag...,190.0
4,2019-07-23,1342bda603bf7ae79af2595951f069db1b50a3cc5dbcc4...,758129001,0.030492,2,2019,7,Tuesday,1,0.0,...,D,Divided,2,Divided,51,Divided Basics,1002,Jersey Basic,Ankle-length dress in soft jersey with a V-nec...,606.0

In [9]:
training_df.columns

Index(['t_dat', 'customer_id', 'article_id', 'price', 'sales_channel_id_x',
       'year', 'month', 'day_of_week', 'interaction_label', 'FN', 'Active',
       'club_member_status', 'fashion_news_frequency', 'age', 'postal_code',
       'purchase_frequency', 'days_since_last_purchase', 'avg_spend',
       'avg_days_between_purchases', 'product_type_name_x', 'season',
       'sales_channel_id_y', 'repeat_purchase_ratio', 'product_code',
       'prod_name', 'product_type_no', 'product_type_name_y',
       'product_group_name', 'graphical_appearance_no',
       'graphical_appearance_name', 'colour_group_code', 'colour_group_name',
       'perceived_colour_value_id', 'perceived_colour_value_name',
       'perceived_colour_master_id', 'perceived_colour_master_name',
       'department_no', 'department_name', 'index_code', 'index_name',
       'index_group_no', 'index_group_name', 'section_no', 'section_name',
       'garment_group_no', 'garment_group_name', 'detail_desc',
       'purchase_count'],
      dtype='object')

In [10]:
training_df = training_df.rename(
    columns={
        'product_type_name_x':
            'favorite_product_type',

        'product_type_name_y':
            'product_type_name',

        'sales_channel_id_x':
            'sales_channel_id'
    }
)

In [11]:
training_df = (
    training_df
    .drop(
        columns=['sales_channel_id_y'],
        errors='ignore'
    )
)

In [12]:
training_df.columns

Index(['t_dat', 'customer_id', 'article_id', 'price', 'sales_channel_id',
       'year', 'month', 'day_of_week', 'interaction_label', 'FN', 'Active',
       'club_member_status', 'fashion_news_frequency', 'age', 'postal_code',
       'purchase_frequency', 'days_since_last_purchase', 'avg_spend',
       'avg_days_between_purchases', 'favorite_product_type', 'season',
       'repeat_purchase_ratio', 'product_code', 'prod_name', 'product_type_no',
       'product_type_name', 'product_group_name', 'graphical_appearance_no',
       'graphical_appearance_name', 'colour_group_code', 'colour_group_name',
       'perceived_colour_value_id', 'perceived_colour_value_name',
       'perceived_colour_master_id', 'perceived_colour_master_name',
       'department_no', 'department_name', 'index_code', 'index_name',
       'index_group_no', 'index_group_name', 'section_no', 'section_name',
       'garment_group_no', 'garment_group_name', 'detail_desc',
       'purchase_count'],
      dtype='object')

In [13]:
selected_columns = [

    'customer_id',
    'article_id',

    'age',

    'purchase_frequency',
    'days_since_last_purchase',
    'avg_spend',
    'avg_days_between_purchases',
    'repeat_purchase_ratio',

    'favorite_product_type',
    'product_type_name',

    'season',
    'sales_channel_id',

    'purchase_count',

    'month',
    'day_of_week',

    'interaction_label'
]

training_df = (
    training_df[
        selected_columns
    ]
)

training_df.head()

,customer_id,article_id,age,purchase_frequency,days_since_last_purchase,avg_spend,avg_days_between_purchases,repeat_purchase_ratio,favorite_product_type,product_type_name,season,sales_channel_id,purchase_count,month,day_of_week,interaction_label
0,0bae744d492a1ee45460ef798a977b33ffa09f14f92cf6...,632307002,23.0,8.0,295.0,0.030057,13.857143,0.000000,Blazer,Top,Autumn,1,1846.0,10,Thursday,1
1,a076c84a1df6ecdb4f21bd6bac49ac5e6704aa48340b7c...,688728003,44.0,126.0,11.0,0.024303,5.560000,0.067797,Trousers,Underwear bottom,Autumn,2,3013.0,11,Sunday,1
2,e1262cea5799e7f866272c5b54aeab5641e62926a4bffe...,524529007,48.0,18.0,457.0,0.018544,0.000000,0.000000,Vest top,Vest top,Summer,1,1234.0,6,Sunday,1
3,17c6855702b6e50f732bee25ef6789927dc3cb61161dfc...,800529001,32.0,219.0,6.0,0.026946,3.041284,0.038095,Dress,Trousers,Summer,2,190.0,1,Thursday,1
4,1342bda603bf7ae79af2595951f069db1b50a3cc5dbcc4...,758129001,28.0,97.0,17.0,0.033973,7.281250,0.054348,Dress,Dress,Winter,2,606.0,7,Tuesday,1

In [14]:
text_cols = [
    'favorite_product_type',
    'product_type_name',
    'season'
]

training_df[
    text_cols
] = (
    training_df[
        text_cols
    ]
    .fillna("Unknown")
)

numeric_cols = [
    'age',
    'purchase_frequency',
    'days_since_last_purchase',
    'avg_spend',
    'avg_days_between_purchases',
    'repeat_purchase_ratio',
    'purchase_count'
]

training_df[
    numeric_cols
] = (
    training_df[
        numeric_cols
    ]
    .fillna(0)
)

In [15]:
training_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 16 columns):
 #   Column                      Non-Null Count    Dtype
---  ------                      --------------    -----
 0   customer_id                 1000000 non-null  object
 1   article_id                  1000000 non-null  int64
 2   age                         1000000 non-null  float64
 3   purchase_frequency          1000000 non-null  float64
 4   days_since_last_purchase    1000000 non-null  float64
 5   avg_spend                   1000000 non-null  float64
 6   avg_days_between_purchases  1000000 non-null  float64
 7   repeat_purchase_ratio       1000000 non-null  float64
 8   favorite_product_type       1000000 non-null  object
 9   product_type_name           1000000 non-null  object
 10  season                      1000000 non-null  object
 11  sales_channel_id            1000000 non-null  int64
 12  purchase_count              1000000 non-null  float64
 13  month                       1000000 non-null  int32
 14  day_of_week                 1000000 non-null  object
 15  interaction_label           1000000 non-null  int64
dtypes: float64(7), int32(1), int64(3), object(5)
memory usage: 118.3+ MB

In [16]:
training_df.to_parquet(
    "/kaggle/working/training_dataset.parquet",
    index=False
)

print("Training dataset saved!")

Training dataset saved!